# Generated by Django 3.2 on 2024-10-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='graduation',
            field=models.FileField(blank=True, null=True, upload_to='graduation/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='high_school',
            field=models.FileField(blank=True, null=True, upload_to='high_school/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='intermediate',
            field=models.FileField(blank=True, null=True, upload_to='intermediate/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post_graduation',
            field=models.FileField(blank=True, null=True, upload_to='post_graduation/'),
        ),
    ]
