# Generated by Django 3.2 on 2024-10-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0002_auto_20241021_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='other_qualification',
            field=models.FileField(blank=True, null=True, upload_to='other_qualification/'),
        ),
    ]
