# Generated by Django 4.2.16 on 2024-11-07 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0004_loginlogouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='claim',
            name='last_action',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
