# Generated by Django 4.2.16 on 2024-11-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0005_claim_approved_by_claim_comment_claim_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
    ]
