# Generated by Django 4.2.16 on 2024-11-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0006_leave_leave_comment_leave_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('half_day_type', models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half')], max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='category',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('without_pay', 'Leave Without Pay'), ('manager_approval', 'Manager Approval')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bluethinkapp.leavetype'),
        ),
    ]
