# Generated by Django 4.2.16 on 2024-11-28 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluethinkapp', '0007_leavetype_leave_category_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
