# Generated by Django 4.2.16 on 2024-11-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0009_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluethinkapp.employee'),
        ),
    ]
