# Generated by Django 4.2.16 on 2024-12-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0010_alter_claim_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='work_hours',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='bluethinkapp.project'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='bluethinkapp.employee'),
        ),
    ]
