# Generated by Django 4.2.16 on 2024-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0014_alter_timesheet_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.CharField(choices=[('Python_Training_on_bench', 'Python_Training_on_bench'), ('On Bench', 'On Bench'), ('Other', 'Other')], default='Python_Training_on_bench', max_length=100),
        ),
    ]
