# Generated by Django 4.2.16 on 2024-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0016_role_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('billable', 'Billable'), ('non_billable', 'Non-Billable')], default='Billable', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
