# Generated by Django 4.2.16 on 2024-12-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0017_project_project_type_project_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='vendor',
            new_name='vendor_name',
        ),
    ]
