# Generated by Django 4.2.16 on 2024-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0018_rename_name_project_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('inactive', 'Inactive'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], max_length=20),
        ),
    ]
