# Generated by Django 4.2.16 on 2024-12-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0021_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfromhome',
            name='work_preference',
            field=models.CharField(choices=[('WFH', 'Work From Home'), ('WFO', 'Work From Office')], default='WFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half'), ('second_half', 'Second Half'), ('full_day', 'Full Day')], max_length=20, null=True),
        ),
    ]
