# Generated by Django 4.2.16 on 2024-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0022_workfromhome_work_preference_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
