# Generated by Django 4.2.16 on 2024-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0023_timesheet_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='acknowledgment',
            field=models.BooleanField(default=False),
        ),
    ]
