# Generated by Django 4.2.16 on 2024-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0024_timesheet_acknowledgment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('weekend', 'Weekend'), ('holiday', 'Holiday'), ('rejected', 'Rejected')], default='present', max_length=20),
        ),
    ]
