# Generated by Django 4.2.16 on 2025-01-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0025_alter_leave_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Camera', 'Camera'), ('Phone', 'Phone')], max_length=20)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='bluethinkapp.employee')),
            ],
        ),
    ]
