# Generated by Django 4.2.16 on 2025-01-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0026_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluethinkapp.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluethinkapp.employee')),
            ],
        ),
    ]
