# Generated by Django 4.2.16 on 2025-01-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0027_assigneddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigneddevice',
            name='category',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Camera', 'Camera'), ('Phone', 'Phone')], default='PC', max_length=100),
        ),
    ]
