# Generated by Django 4.2.16 on 2025-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0028_assigneddevice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
