# Generated by Django 4.2.16 on 2025-01-07 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0030_projectassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
