# Generated by Django 4.2.16 on 2025-01-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0031_alter_projectassignment_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='assigned_project',
            field=models.ForeignKey(blank=True, help_text='Select a project from the available list', null=True, on_delete=django.db.models.deletion.CASCADE, to='bluethinkapp.project'),
        ),
    ]
