# Generated by Django 4.2.16 on 2025-01-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0033_alter_timesheet_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bluethinkapp.employee'),
        ),
    ]
