# Generated by Django 4.2.16 on 2025-01-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0034_project_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='project',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='assigned_project',
            field=models.ForeignKey(default=1, help_text='Select a project from the available list', on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='bluethinkapp.project'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='custom_project_name',
            field=models.CharField(blank=True, help_text='Enter a custom project name if applicable', max_length=100, null=True),
        ),
    ]
