# Generated by Django 4.2.16 on 2025-01-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0035_remove_timesheet_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='bluethinkapp.employee'),
        ),
    ]
