# Generated by Django 4.2.16 on 2025-01-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0037_alter_project_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to='bluethinkapp.employee'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='assigned_project',
            field=models.ForeignKey(help_text='Select a project from the available list', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='bluethinkapp.project'),
        ),
    ]
