# Generated by Django 4.2.16 on 2025-01-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0038_alter_project_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='assigned_project',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='project_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='bluethinkapp.projectassignment'),
        ),
    ]
