# Generated by Django 4.2.16 on 2025-01-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0039_remove_timesheet_assigned_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='custom_project_name',
        ),
    ]
