# Generated by Django 4.2.16 on 2025-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0041_teamlead_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='parent_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bluethinkapp.teammember'),
        ),
    ]
