# Generated by Django 4.2.16 on 2025-01-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0042_teammember_parent_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='subordinates',
            field=models.ManyToManyField(blank=True, related_name='subordinates', to='bluethinkapp.employee'),
        ),
    ]
