# Generated by Django 4.2.16 on 2025-01-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0043_teammember_subordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='subordinates',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='parent_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='bluethinkapp.teammember'),
        ),
    ]
