# Generated by Django 4.2.19 on 2025-02-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0044_remove_teammember_subordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='per_day_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
