# Generated by Django 4.2.19 on 2025-02-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0045_employee_per_day_salary_employee_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='per_day_salary',
            new_name='salary_per_day',
        ),
    ]
