# Generated by Django 4.2.19 on 2025-02-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0046_rename_per_day_salary_employee_salary_per_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Training',
        ),
    ]
