# Generated by Django 4.2.19 on 2025-02-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0047_delete_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
