# Generated by Django 4.2.19 on 2025-02-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0048_employee_base_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
