# Generated by Django 4.2.19 on 2025-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0050_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='total_absent_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_leave_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_present_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryslip',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
