# Generated by Django 4.2.19 on 2025-02-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0051_salaryslip_total_absent_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryslip',
            old_name='total_absent_day',
            new_name='total_absent_days',
        ),
        migrations.RenameField(
            model_name='salaryslip',
            old_name='total_leave_day',
            new_name='total_leave_days',
        ),
        migrations.RenameField(
            model_name='salaryslip',
            old_name='total_present_day',
            new_name='total_present_days',
        ),
    ]
