# Generated by Django 4.2.19 on 2025-02-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0052_rename_total_absent_day_salaryslip_total_absent_days_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalarySlip',
            new_name='SalaryS',
        ),
    ]
