# Generated by Django 4.2.19 on 2025-02-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0053_rename_salaryslip_salarys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalaryS',
            new_name='SalarySlip',
        ),
    ]
