# Generated by Django 4.2.19 on 2025-02-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0054_rename_salarys_salaryslip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryslip',
            name='total_absent_days',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='total_leave_days',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='total_present_days',
        ),
        migrations.RemoveField(
            model_name='salaryslip',
            name='total_salary',
        ),
    ]
