# Generated by Django 4.2.19 on 2025-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluethinkapp', '0055_remove_salaryslip_total_absent_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryslip',
            name='total_absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
